### ISSUE TITLE
Crashing with Frida detection 

### ISSUE THREAD

**Issue by barkatthemoon18** [darvincisec/AntiDebugandMemoryDump#1]
Greetings.

The inotify when is watching the /proc/self/maps crashes when is working alongside Frida detection which reads the file and when the verification is done (by checking the flags IN_ACCESS or IN_OPEN), the crash occurs. 
When I remove the watcher for /proc/self/maps or not load the Frida detection on the current process (application process) it works fine.

**Comment by darvincisec** [comment]
@fnazal18, Yes i mentioned in the readme about this issue. I havent tried out the solution i was thinking of. Will update it here once done. PRs welcome though

**Comment by barkatthemoon18** [comment]
Didn't check it. I will try to avoid it and if works I'll be glad to do some PR. Thanks a lot!
